[package]
name = "game"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[profile.release]
debug = true
opt-level = 3
lto = true

[dependencies]
bevy = "0.5"
gdnative = "0.9"
byteorder = "1.4.3"
